### ISSUE TITLE
Using your code

### ISSUE THREAD

**Issue by fabiendelpierre** [gchef/rtorrent-cookbook#2]
Hi @gerhard,
This isn't so much an issue with this cookbook as a general question. I wanted to email you directly but you did a good job concealing your email address around the Internet!
To give you some background info, I was working on setting up a Linux box with rTorrent and wanted to manage everything on the box through Chef. To save time, I tried to find existing rTorrent/ruTorrent cookbooks and found yours. I tried using it but it didn't fit my use case and because I'm a beginner at Ruby, a lot of your code confused me. I had initially forked this repo but it didn't work out for me, so I ended up putting together my own cookbook, which I plan to release as open source soon. I am using bits and pieces from your code within mine, and there's no license information in this repo, so just to be safe, I wanted to ask you if you're OK with me using bits and pieces of your code. I am making it clear in my repo that I'm not the sole author.
Thanks!

**Comment by gerhard** [comment]
Sure, happy for you to use any part of it that you want. Glad to hear that bits of it were useful :wink:

**Comment by fabiendelpierre** [comment]
Thank you for your prompt answer!
